name: Deploy to GitHub Pages

on: push        # se déclenche à chaque push
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with:
          path: .              # répertoire publié (racine ici)
      - uses: actions/deploy-pages@v4
